backend:
  name: github
  repo: josbri/josep-blog
media_folder: static/blog/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: static/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: title, label: Title, widget: string, required: true }
      - { name: body, label: Body, widget: markdown }
