backend:
  name: github
  repo: josbri/josep-blog
media_folder: static/blog/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: static/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - {
          name: tags,
          label: Tags,
          widget: relation,
          collection: "categories",
          searchFields: name,
          valueField: name,
          multiple: true,
          min: 1,
        }
      - { name: title, label: Title, widget: string, required: true }
      - { name: slug, lable: Slug, widget: string, required: true }
      - { name: body, label: Body, widget: markdown }
      - { name: type, label: Type, widget: "hidden", default: "blog" }

  - name: categories
    label: Categories
    folder: static/categories
    media_folder: assets
    public_folder: assets
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - { name: name, label: Name, widget: string, required: true }
      - { name: logo, label: Logo, widget: image, required: true }
      - { name: type, label: Type, widget: "hidden", default: "category" }

  - name: portfolio
    label: Portfolio
    folder: static/portfolio
    media_folder: assets
    public_folder: assets
    create: true
    fields:
      - { name: type, label: Type, widget: "hidden", default: "portfolio" }
      - { name: title, label: Title, widget: string, required: true }
      - { name: slug, lable: Slug, widget: string, required: true }
      - {
          name: area,
          label: Area,
          widget: select,
          multiple: true,
          options: ["Front-End", "Back-End", "Mobile"],
          min: 1,
        }
      - { name: link, label: "Link", widget: string }
      - { name: image, label: Image, widget: image }
      - { name: technologies, label: Technology, widget: list }
      - { name: description, label: Description, widget: markdown }
      - { name: body, label: Body, widget: markdown }
