backend:
  name: github
  repo: josbri/josep-blog
media_folder: static/blog/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: static/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - {
          name: tags,
          label: Tags,
          widget: relation,
          collection: "categories",
          searchFields: name,
          valueField: name,
          multiple: true,
          min: 1,
        }
      - { name: title, label: Title, widget: string, required: true }
      - { name: slug, lable: Slug, widget: string, required: true }
      - { name: body, label: Body, widget: markdown }

  - name: categories
    label: Categories
    folder: static/categories
    create: true
    fields:
      - { name: name, label: Name, widget: string, required: true }
      - { name: logo, label: Logo, widget: image, required: true }
